name: Build & Test
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    ci:
        uses: DCC-BS/ci-workflows/.github/workflows/ci.yml@d64a5d501aaee55d37be82405e03812862d43474
